apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: iso8583-console:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: console-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"