---
apiVersion: v1
kind: Service
metadata:
  name: iso8583-service
  labels:
    app: iso8583-server
spec:
  selector:
    app: iso8583-server
  ports:
    - name: iso8583
      protocol: TCP
      port: 8583
      targetPort: 8583
  type: ClusterIP   
